openapi: 3.0.1
info:
  title: TIKI API
  description: TIKI's REST API
  license:
    name: MIT
    url: https://github.com/tiki/core/blob/main/LICENSE
  version: 1.0.0
servers:
  - url: https://mytiki.com/api/{version}
    variables:
      version:
        default: latest

security:
  - addressToken: []

paths:
  /trail/licenses:
    post:
      security:
        - addressToken: []
      summary: Create License
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLicense"
      responses:
        "201":
          description: Created
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/License"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspError"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspError"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspError"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspError"
  /trail/licenses/verify:
    post:
      security:
        - addressToken: []
      summary: Check if the license is Verify
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostLicenseVerify"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspLicenseVerify"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspError"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspError"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspError"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RspError"

components:
  securitySchemes:
    addressToken:
      type: oauth2
      description: See https://mytiki.com/reference/authorization#address-token
      flows:
        clientCredentials:
          tokenUrl: https://account.mytiki.com/api/latest/auth
          scopes: {}

  schemas:
    Title:
      type: object
      properties:
        id:
          type: string
        ptr:
          type: string
        tags:
          type: array
          items:
            type: string
        timestamp:
          type: string
          format: date-time
        description:
          type: string

    License:
      type: object
      properties:
        id:
          type: string
        title:
          $ref: "#/components/schemas/Title"
        uses:
          type: array
          items:
            $ref: "#/components/schemas/Usecase"
        terms:
          type: string
        timestamp:
          type: string
          format: date-time
        description:
          type: string
        expiry:
          type: string
          format: date-time

    CreateLicense:
      type: object
      required:
        - ptr
        - tags
        - uses
        - terms
        - licenseDesc
      properties:
        ptr:
          type: string
        tags:
          type: array
          items:
            type: string
        uses:
          $ref: "#/components/schemas/Use"
        terms:
          type: string
        licenseDesc:
          type: string
        titleDesc:
          type: string
        expiry:
          type: string
          format: date-time
          
    RspError:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    PostLicenseVerify:
      type: object
      properties:
        ptr:
          type: string
        usecases:
          type: array
          items:
            type: string
        destinations:
          type: array
          items:
            type: string

    RspLicenseVerify:
      type: object
      properties:
        success:
          type: boolean
        reason:
          type: string

    Use:
      type: object
      properties:
        usecases:
          type: array
          items:
            $ref: "#/components/schemas/Usecase"
        destinations:
          type: array
          items:
            type: string
      required:
        - usecases

    Usecase:
      type: object
      properties:
        value:
          type: string
      required:
        - value
