name: tiki_sdk_dart
description: TIKI's decentralized infrastructure plus abstractions to simplify the tokenization and application of data ownership, consent, and rewards. 
version: 1.1.2
homepage: https://mytiki.com
documentation: https://docs.mytiki.com/docs/tiki-sdk-dart-getting-started
repository: https://github.com/tiki/tiki-sdk-dart
issue_tracker: https://github.com/tiki/tiki-sdk-dart/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  pointycastle: ^3.6.1
  sqlite3: ^1.7.2
  http: ^0.13.5
  html: ^0.15.0
  uuid: ^3.0.6
  nock: ^1.2.1
  idb_sqflite: ^1.3.0

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.1
  build_web_compilers: ^3.2.7
  build_runner: ">=1.6.2 <3.0.0"


